"""Add created_at timestamp to User model

Revision ID: 070f60ea361e
Revises: d7ffc9f06eef
Create Date: 2026-05-10 20:22:28.460056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070f60ea361e'
down_revision = 'd7ffc9f06eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
